#!/usr/bin/env node
"use strict";

const fs = require("node:fs");
const path = require("node:path");

const {
  latestFileMatching,
  listTopicSlugs,
  readJsonIfExists,
} = require("./lib/topic-utils");

const ROOT = path.join(__dirname, "..");
const TOPICS_DIR = path.join(ROOT, "topics");
const META_DIR = path.join(TOPICS_DIR, "_meta");

function dash(value) {
  return value === null || value === undefined || value === "" ? "-" : String(value);
}

function latestBenchReport() {
  const latest = latestFileMatching(META_DIR, /^bench-report-\d{4}-\d{2}-\d{2}\.md$/);
  if (!latest) return null;
  const content = fs.readFileSync(latest, "utf8");
  const meanMatch = content.match(/\| Mean final score \| ([^|]+) \|/);
  const completeMatch = content.match(/\| Complete \| ([^|]+) \|/);
  return {
    path: latest,
    meanFinalScore: meanMatch ? meanMatch[1].trim() : null,
    complete: completeMatch ? completeMatch[1].trim() : null,
  };
}

function citationForTopic(slug) {
  const latest = latestFileMatching(path.join(TOPICS_DIR, slug, "_pipeline"), /^citation-check-\d{4}-\d{2}-\d{2}\.json$/);
  const report = latest ? readJsonIfExists(latest) : null;
  if (!report || report.__parseError) {
    return { slug, checked_on: null, total: 0, ok: 0, failed: 0, warnings: 0 };
  }
  return {
    slug,
    checked_on: report.checked_on,
    total: report.total_urls ?? 0,
    ok: (report.ok ?? 0) + (report.redirect_ok ?? 0),
    failed: (report.dead ?? 0) + (report.timeout ?? 0) + (report.error ?? 0) + (report.blocked ?? 0) + (report.dns_error ?? 0),
    warnings: (report.warn_auth ?? 0) + (report.warn_placeholder ?? 0),
  };
}

function buildReport() {
  const today = new Date().toISOString().slice(0, 10);
  const slugs = listTopicSlugs(TOPICS_DIR);
  const bench = latestBenchReport();
  const citations = slugs.map(citationForTopic);
  const totalUrls = citations.reduce((sum, item) => sum + item.total, 0);
  const failedUrls = citations.reduce((sum, item) => sum + item.failed, 0);
  const warningUrls = citations.reduce((sum, item) => sum + item.warnings, 0);

  const lines = [];
  lines.push("---");
  lines.push("title: BrainStorming Trend Report");
  lines.push(`created: ${today}`);
  lines.push("tags: [meta, trends]");
  lines.push("---");
  lines.push("");
  lines.push(`# BrainStorming Trend Report - ${today}`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push("| Metric | Value |");
  lines.push("| --- | ---: |");
  lines.push(`| Published topics | ${slugs.length} |`);
  lines.push(`| Complete topics in latest benchmark | ${dash(bench?.complete)} |`);
  lines.push(`| Mean final score in latest benchmark | ${dash(bench?.meanFinalScore)} |`);
  lines.push(`| Citation URLs checked | ${totalUrls} |`);
  lines.push(`| Citation failures | ${failedUrls} |`);
  lines.push(`| Citation warnings | ${warningUrls} |`);
  lines.push("");
  lines.push("## Citation Health");
  lines.push("");
  lines.push("| Topic | Checked On | Total | OK/Redirect | Failed | Warnings |");
  lines.push("| --- | --- | ---: | ---: | ---: | ---: |");
  for (const item of citations) {
    lines.push(`| ${item.slug} | ${dash(item.checked_on)} | ${item.total} | ${item.ok} | ${item.failed} | ${item.warnings} |`);
  }
  lines.push("");
  lines.push("## Inputs");
  lines.push("");
  lines.push(`- Latest benchmark report: ${bench ? path.relative(ROOT, bench.path).replace(/\\/g, "/") : "not found"}`);
  lines.push("- Citation data: latest per-topic `topics/{slug}/_pipeline/citation-check-YYYY-MM-DD.json` when available");
  lines.push("");
  lines.push(`*Generated by scripts/trend-report.js | ${today}*`);
  return { today, markdown: lines.join("\n") };
}

fs.mkdirSync(META_DIR, { recursive: true });
const { today, markdown } = buildReport();
const outPath = path.join(META_DIR, `trend-report-${today}.md`);
fs.writeFileSync(outPath, markdown, "utf8");
console.log(`Trend report written: ${outPath}`);
